-- Generated by Supabase
-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.analysis_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_analysis_id uuid,
  metric_name text,
  user_score double precision,
  benchmark_score double precision,
  CONSTRAINT analysis_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT analysis_metrics_job_analysis_id_fkey FOREIGN KEY (job_analysis_id) REFERENCES public.job_analysis(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  company_name text NOT NULL,
  CONSTRAINT companies_pkey PRIMARY KEY (id),
  CONSTRAINT companies_id_fkey FOREIGN KEY (id) REFERENCES public.users(id)
);
CREATE TABLE public.company_profiles (
  id uuid NOT NULL,
  company_name text NOT NULL,
  company_website text,
  logo_url text,
  email text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  description text,
  company_id uuid,
  CONSTRAINT company_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT company_profiles_id_fkey FOREIGN KEY (id) REFERENCES public.companies(id)
);
CREATE TABLE public.competitor_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_analysis_id uuid,
  source text,
  extracted_data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT competitor_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT competitor_profiles_job_analysis_id_fkey FOREIGN KEY (job_analysis_id) REFERENCES public.job_analysis(id)
);
CREATE TABLE public.course_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  course_id uuid,
  used_at timestamp with time zone DEFAULT now(),
  CONSTRAINT course_usage_pkey PRIMARY KEY (id),
  CONSTRAINT course_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT course_usage_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id)
);
CREATE TABLE public.courses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text,
  skill_category text,
  affiliate_link text,
  discount_code text DEFAULT 'RESUME10'::text,
  CONSTRAINT courses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cover_letters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  resume_id uuid,
  title character varying,
  content text,
  type text,
  job_position character varying,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT cover_letters_pkey PRIMARY KEY (id),
  CONSTRAINT cover_letters_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT cover_letters_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id)
);
CREATE TABLE public.embedding (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type text,
  entity_id uuid,
  vector USER-DEFINED NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT embedding_pkey PRIMARY KEY (id)
);
CREATE TABLE public.job_analysis (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  resume_id uuid,
  output_score integer,
  top_missing_skills ARRAY,
  top_advice ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  competitor_profiles_id uuid,
  CONSTRAINT job_analysis_pkey PRIMARY KEY (id),
  CONSTRAINT job_analysis_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT job_analysis_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT job_analysis_competitor_profiles_id_fkey FOREIGN KEY (competitor_profiles_id) REFERENCES public.competitor_profiles(id)
);
CREATE TABLE public.job_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid,
  candidate_id uuid,
  status text DEFAULT 'pending'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT job_invitations_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.job_posting(id),
  CONSTRAINT job_invitations_candidate_id_fkey FOREIGN KEY (candidate_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.job_matches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  job_id uuid,
  match_score double precision NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  status text DEFAULT 'matched'::text,
  resume_id uuid,
  cover_letter_id uuid,
  CONSTRAINT job_matches_pkey PRIMARY KEY (id),
  CONSTRAINT job_matches_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT job_matches_cover_letter_id_fkey FOREIGN KEY (cover_letter_id) REFERENCES public.cover_letters(id),
  CONSTRAINT job_matches_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT job_matches_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.job_posting(id)
);
CREATE TABLE public.job_posting (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name text,
  job_title text,
  required_skills ARRAY,
  is_active boolean DEFAULT true,
  company_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_posting_pkey PRIMARY KEY (id),
  CONSTRAINT job_posting_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.market_insights_cache (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_title text NOT NULL DEFAULT ''::text,
  company_name text,
  search_query text UNIQUE,
  raw_scraps jsonb,
  key_skills ARRAY,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT market_insights_cache_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscription_id uuid,
  user_id uuid,
  amount numeric NOT NULL,
  currency text DEFAULT 'USD'::text,
  stripe_payment_intent_id text UNIQUE,
  status text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id),
  CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.resume_feedback (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  resume_id uuid NOT NULL,
  overall_score integer CHECK (overall_score >= 0 AND overall_score <= 100),
  content_score integer,
  formatting_score integer,
  ats_compatibility_score integer,
  suggestions jsonb,
  critical_fixes ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  learning_path jsonb,
  skill_gaps ARRAY,
  CONSTRAINT resume_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT resume_feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT resume_feedback_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id)
);
CREATE TABLE public.resumes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  raw_content jsonb,
  polished_content jsonb,
  target_job_title text,
  premium_analysis boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  template_id uuid,
  temp_token uuid DEFAULT gen_random_uuid(),
  ai_market_insights jsonb,
  ai_learning_recommendations jsonb,
  last_analysis_id uuid,
  CONSTRAINT resumes_pkey PRIMARY KEY (id),
  CONSTRAINT resumes_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.templates(id),
  CONSTRAINT resumes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT resumes_last_analysis_id_fkey FOREIGN KEY (last_analysis_id) REFERENCES public.resume_feedback(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  plan text NOT NULL,
  status text NOT NULL,
  price numeric,
  start_date timestamp with time zone DEFAULT now(),
  end_date timestamp with time zone,
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  type text NOT NULL,
  preview_image_url text,
  style_config jsonb NOT NULL,
  is_premium boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_analysis_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  resume_id uuid,
  match_score integer,
  skill_gap_analysis jsonb,
  created_at timestamp with time zone DEFAULT now(),
  cv_embedding_id uuid,
  CONSTRAINT user_analysis_history_pkey PRIMARY KEY (id),
  CONSTRAINT user_analysis_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_analysis_history_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT user_analysis_history_cv_embedding_id_fkey FOREIGN KEY (cv_embedding_id) REFERENCES public.embedding(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  full_name text,
  avatar_url text,
  tier text DEFAULT 'free'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  name character varying,
  email character varying NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  company_id uuid,
  role text DEFAULT 'user'::text,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);