-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.
-- Generated by Supabase

CREATE TABLE public.company_profiles (
  id uuid NOT NULL,
  company_name text NOT NULL,
  company_website text,
  logo_url text,
  contact_email text,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT partner_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.courses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text,
  skill_category text,
  affiliate_link text,
  discount_code text DEFAULT 'RESUME10'::text,
  CONSTRAINT courses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cover_letters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  resume_id uuid,
  title character varying,
  content text,
  type text,
  job_position character varying,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT cover_letters_pkey PRIMARY KEY (id),
  CONSTRAINT cover_letters_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT cover_letters_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id)
);
CREATE TABLE public.job_analysis (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  resume_id uuid,
  output_score integer,
  top_missing_skills ARRAY,
  top_advice ARRAY,
  competitor_analysis text,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  CONSTRAINT job_analysis_pkey PRIMARY KEY (id),
  CONSTRAINT job_analysis_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id),
  CONSTRAINT job_analysis_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.job_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid,
  candidate_id uuid,
  status text DEFAULT 'pending'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT job_invitations_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.job_posting(id),
  CONSTRAINT job_invitations_candidate_id_fkey FOREIGN KEY (candidate_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.job_posting (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name text,
  job_title text,
  required_skills ARRAY,
  is_active boolean DEFAULT true,
  company_id uuid NOT NULL,
  CONSTRAINT job_posting_pkey PRIMARY KEY (id),
  CONSTRAINT partner_job_postings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.company_profiles(id)
);
CREATE TABLE public.market_insights_cache (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_title text NOT NULL DEFAULT,
  company_name text,
  search_query text UNIQUE,
  raw_scraps jsonb,
  key_skills ARRAY,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT market_insights_cache_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscription_id uuid,
  user_id uuid,
  amount numeric NOT NULL,
  currency text DEFAULT 'USD'::text,
  stripe_payment_intent_id text UNIQUE,
  status text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id),
  CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.resume_feedback (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  resume_id uuid NOT NULL,
  overall_score integer CHECK (overall_score >= 0 AND overall_score <= 100),
  content_score integer,
  formatting_score integer,
  ats_compatibility_score integer,
  suggestions jsonb,
  critical_fixes ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT resume_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT resume_feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT resume_feedback_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id)
);
CREATE TABLE public.resumes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  raw_content jsonb,
  polished_content jsonb,
  target_job_title text,
  target_job_description text,
  premium_analysis boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  template_id uuid,
  CONSTRAINT resumes_pkey PRIMARY KEY (id),
  CONSTRAINT resumes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT resumes_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.templates(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  plan text NOT NULL,
  status text NOT NULL,
  price numeric,
  start_date timestamp with time zone DEFAULT now(),
  end_date timestamp with time zone,
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  type text NOT NULL,
  preview_image_url text,
  style_config jsonb NOT NULL,
  is_premium boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_analysis_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  resume_id uuid,
  match_score integer,
  skill_gap_analysis jsonb,
  cv_embedding USER-DEFINED,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_analysis_history_pkey PRIMARY KEY (id),
  CONSTRAINT user_analysis_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_analysis_history_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  full_name text,
  avatar_url text,
  current_tier text DEFAULT 'free'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  name character varying,
  email character varying NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);