-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.
-- Generated by Supabase

CREATE TABLE public.cover_letters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  resume_id uuid,
  title character varying,
  content text,
  type text,
  job_position character varying,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT cover_letters_pkey PRIMARY KEY (id),
  CONSTRAINT cover_letters_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT cover_letters_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id)
);
CREATE TABLE public.job_analysis (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  resume_id uuid,
  output_score integer,
  top_missing_skills ARRAY,
  top_advice ARRAY,
  competitor_analysis text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_analysis_pkey PRIMARY KEY (id),
  CONSTRAINT job_analysis_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id)
);
CREATE TABLE public.market_insights_cache (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  job_title text NOT NULL,
  company_name text,
  search_query text UNIQUE,
  raw_scraps jsonb,
  key_skills ARRAY,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT market_insights_cache_pkey PRIMARY KEY (id)
);
CREATE TABLE public.resume_feedback (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  resume_id uuid NOT NULL,
  overall_score integer CHECK (overall_score >= 0 AND overall_score <= 100),
  content_score integer,
  formatting_score integer,
  ats_compatibility_score integer,
  suggestions jsonb,
  critical_fixes ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT resume_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT resume_feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT resume_feedback_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id)
);
CREATE TABLE public.resumes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  raw_content jsonb,
  polished_content jsonb,
  target_job_title text,
  target_job_description text,
  premium_analysis boolean DEFAULT false,
  template_id integer,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT resumes_pkey PRIMARY KEY (id),
  CONSTRAINT resumes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_analysis_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  resume_id uuid,
  match_score integer,
  skill_gap_analysis jsonb,
  cv_embedding USER-DEFINED,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_analysis_history_pkey PRIMARY KEY (id),
  CONSTRAINT user_analysis_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_analysis_history_resume_id_fkey FOREIGN KEY (resume_id) REFERENCES public.resumes(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  name character varying,
  email character varying NOT NULL UNIQUE,
  tier character varying DEFAULT 'free'::character varying,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);